<!-- This is a link to the home page html file page -->
<div id="Logo" class="HeaderLogoLayout HeaderLogoStyle">

	<a href="index.php" class="NoUnderLineForLink">Valyouation</a>

</div>

<!-- This is a link to the motivation html file page -->
<div id="Motivation" class="HeaderMotivationLayout HeaderMotivationStyle">

  	<a href="SourceCode/HTML/HTMLbody/Header/Motivation/Motivation.html" class="NoUnderLineForLink">Motivation</a>

</div>

<!-- This is a link to the how it works html file page -->
<div id="HowItWorks" class="HeaderHowItWorksLayout HeaderHowItWorksStyle">

  	<a href="SourceCode/HTML/HTMLbody/Header/HowItWorks/HowItWorks.html" class="NoUnderLineForLink">How it works</a>

</div>

<!-- This is a link to the profile in html file page -->
<div id="Profile" class="HeaderProfileLayout HeaderProfileStyle">

  	<a href="SourceCode/HTML/HTMLbody/Header/HeaderLoggedUser.html" class="NoUnderLineForLink">Profile</a>

</div>


